services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - /app/node_modules
      - ./uploads:/app/uploads:delegated,ro
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 2048m
    environment:
      - NODE_ENV=development
      # Core GDAL settings for viewshed
      - GDAL_CACHEMAX=4096
      - GDAL_NUM_THREADS=ALL_CPUS
      # Python settings
      - PYTHONUNBUFFERED=1
    command: yarn start:dev
